= NixOS-Qubes

This repository is intended for the initial development and testing of QubesOS packages and modules for NixOS.

It is planned that it will be merged to NixOS later, previous version of that work (here https://github.com/NixOS/nixpkgs/pull/341215) was stalled because
it is a little too hard to maintain all of this in-tree.

== Initial setup

Get it started somehow

The default setup has no templates installed, but nixos-qubes-tools to your rescue

Get qubes RPM gpg key from a trusted location, e.g: https://keys.qubes-os.org/keys/qubes-release-4.3-signing-key.asc

Install fedora kernel required for fedora templates:

[source,bash]
----
nixos-qubes-install-kernel-url 6.12.64-1.fc41 6.12.64-1 fc41 \
  https://ftp.qubes-os.org/repo/yum/r4.3/current/dom0/fc41/rpm/kernel-qubes-vm-6.12.64-1.qubes.fc41.x86_64.rpm \
  https://ftp.qubes-os.org/repo/yum/r4.3/current/dom0/fc41/rpm/kernel-modules-6.12.64-1.qubes.fc41.x86_64.rpm \
  qubes-release-4.3-signing-key.asc
----

Set it as default:

[source,bash]
----
qubes-prefs default_kernel 6.12.64-1.fc41
----

Install first fedora template, it is required to work as UpdateVM to install other QubesOS templates:

[source,bash]
----
nixos-qubes-install-template-url fedora-43-xfce \
  https://ftp.qubes-os.org/repo/yum/r4.3/templates-itl/rpm/qubes-template-fedora-43-xfce-4.3.0-202601041226.noarch.rpm \
  qubes-release-4.3-signing-key.asc
----

(TODO: NixOS based micro-vm with rpm installed to provide template search/download RPC endpoints?)

Set fedora template as default_template:

[source,bash]
----
qubes-prefs default_template fedora-43-xfce
----

Create vm to use as default disposable, mark it as such, and set it:

[source,bash]
----
qvm-create --template fedora-43-xfce --label red default-dvm
qvm-prefs default-dvm template_for_dispvms True
qubes-prefs default_dispvm default-dvm
----

Set update VM:

[source,bash]
----
qubes-prefs updatevm fedora-43-xfce
----
