#!/bin/sh

set -eu

usage() {
	echo "Usage: nixos-qubes-install-template-rpm <template-name> <rpm-file>" >&2
	echo "" >&2
	echo "Installs a Qubes template from a local RPM file." >&2
	echo "" >&2
	echo "Arguments:" >&2
	echo "  template-name  Name of the template (e.g. 'fedora-41-xfce')" >&2
	echo "  rpm-file       Path to the template RPM file" >&2
	exit 1
}

if [ "$#" -ne 2 ]; then
	usage
fi

template_name=$1
template_file=$2

dir=$(mktemp -d)
cd "$dir" || exit 1

rpmextract "$template_file"

srcdir=$dir/var/lib/qubes/vm-templates/$template_name

if ! test -f "$srcdir/template.conf"; then
	echo "template with specified name is not found in rpm"
	exit 1
fi
ln -s "$template_file" "$srcdir/template.rpm"

qvm-template-postprocess --really post-install "$template_name" "$srcdir"
